Repository saddlebackdev/react-cm-ui, pull requests merged in 2020-12, with the labels that each got.

#250 [dev] No PBI - Spread styles object for each columns on Data Card.
  src/dataDisplay/dataCards/dataCardColumn.jsx
Labels: enhancement

#247 [feature/cumulative--10.0.0] AB#33500 - Select Component
  docs/src/app/navigationConstants.js
  docs/src/inputs/select/api/api.jsx
  docs/src/inputs/select/api/index.js
  docs/src/inputs/select/constants.js
  docs/src/inputs/select/devSandbox/devSandbox.jsx
  docs/src/inputs/select/devSandbox/index.js
  docs/src/inputs/select/examples/exampleClearableSelect.jsx
  docs/src/inputs/select/examples/exampleCreatableAdvancedSelect.jsx
  docs/src/inputs/select/examples/exampleCreatableSelect.jsx
  docs/src/inputs/select/examples/exampleDefaultSelect.jsx
  docs/src/inputs/select/examples/exampleDisableSelect.jsx
  docs/src/inputs/select/examples/exampleLabelSelect.jsx
  docs/src/inputs/select/examples/exampleMultipleSelect.jsx
  docs/src/inputs/select/examples/exampleRequiredSelect.jsx
  docs/src/inputs/select/examples/exampleSearchableSelect.jsx
  docs/src/inputs/select/index.js
  docs/src/inputs/select/select.jsx
  src/inputs/select/__test__/select.test.js
  src/inputs/select/select.jsx
Labels: docs

#252 [dev] No PBI - Filters Rail Over Content Fix and Typography Styles Documentation
  docs/src/app/navigationConstants.js
  docs/src/styleGuide/typography.jsx
  docs/src/styleGuide/typographyGridColumn.jsx
  src/surfaces/filtersRail/filtersRail.jsx
Labels: bug, docs

#256 [feature/cumulative--10.0.0] No PBI - Input Number Type Does Not Allow Number To Be Greater Than 1
  src/inputs/input/__test__/input.test.js
  src/inputs/input/input.jsx
Labels: bug, priority medium

#257 [dev] AB#40135 - Removed Grid Container In ActionsBar If `columns` Empty.
  src/dataDisplay/list/listItem.jsx
  src/surfaces/actionBar/actionBar.jsx
Labels: bug

#258 [dev] [No PBI] Update components using `forwardRef` to use named callbacks
  src/layout/grid/grid.jsx
  src/layout/grid/gridColumn.jsx
  src/layout/grid/gridRow.jsx
  src/layout/page/page.jsx
  src/layout/page/pageDetailsWindow.jsx
  src/surfaces/drawer/drawerDetailsWindow.jsx
Labels: enhancement, priority medium

#249 [feature/cumulative--10.0.0] AB#33499 - Closed Tooltip Gap
  docs/src/app/navigationConstants.js
  docs/src/dataDisplay/tooltip/api/api.jsx
  docs/src/dataDisplay/tooltip/api/index.js
  docs/src/dataDisplay/tooltip/examples/exampleButtonsBehaviors.jsx
  docs/src/dataDisplay/tooltip/examples/exampleIconBehaviors.jsx
  docs/src/dataDisplay/tooltip/examples/exampleSelectBehaviors.jsx
  docs/src/dataDisplay/tooltip/tooltip.jsx
  src/dataDisplay/icon/icon.jsx
  src/dataDisplay/tooltip/__test__/tooltip.test.js
  src/dataDisplay/tooltip/tooltip.jsx
  src/global/constants.js
  src/inputs/button/button.jsx
  src/inputs/checkbox/checkbox.jsx
  src/inputs/select/select.jsx
  src/inputs/switch/switch.jsx
  src/utils/dateUtils.js
  src/versions.js
Labels: enhancement, priority high

#259 [dev] AB#36385 - Removed Outline On A's onClick and Enhanced Prompt's tabIndex
  docs/src/inputs/prompt/promptExample.jsx
  src/inputs/prompt/prompt.jsx
  src/inputs/prompt/prompt.scss
  src/navigation/a/__test__/a.test.js
  src/navigation/a/a.jsx
  src/navigation/a/a.scss
  src/style.scss
Labels: bug, enhancement

#260 [dev] AB#40538 - Added View Icon
  docs/src/dataDisplay/icon/icon.jsx
  src/dataDisplay/icon/icon.jsx
Labels: enhancement, priority medium

#261 [dev] No PBI - DataGroups Light Code Clean Up
  src/dataDisplay/dataGroups/dataGroup.jsx
  src/dataDisplay/dataGroups/dataGroupExpandedRow.jsx
  src/dataDisplay/dataGroups/dataGroupRow.jsx
  src/dataDisplay/dataGroups/dataGroups.jsx
  src/dataDisplay/dataGroups/dataGroupsColumn.jsx
  src/dataDisplay/dataGroups/dataGroupsPropTypes.js
Labels: enhancement

#242 [feature/cumulative--10.0.0] AB#33500 - Removed Dropdown Component
  docs/src/app/navigationConstants.js
  docs/src/dataDisplay/comment/comment.jsx
  docs/src/inputs/durationPicker/api/api.jsx
  docs/src/inputs/durationPicker/api/index.js
  docs/src/inputs/durationPicker/durationPicker.jsx
  docs/src/inputs/durationPicker/examples/exampleDurationPickerDaysHoursMinutesSeconds.jsx
  docs/src/inputs/durationPicker/examples/exampleDurationPickerDisabled.jsx
  docs/src/inputs/durationPicker/examples/exampleDurationPickerErrorHandling.jsx
  docs/src/inputs/durationPicker/examples/exampleDurationPickerLabel.jsx
  docs/src/inputs/durationPicker/examples/exampleDurationPickerRequired.jsx
  docs/src/inputs/durationPicker/examples/exampleDurationPickerSimple.jsx
  docs/src/inputs/durationPicker/examples/exampleDurationPickerYearsMonthsDays.jsx
  src/dataDisplay/banner/__test__/banner.test.js
  src/dataDisplay/banner/banner.jsx
  src/dataDisplay/comment/comment.jsx
  src/dataDisplay/headerDeprecated/__test__/headerDeprecated.test.js
  src/index.js
  src/inputs/button/button.jsx
  src/inputs/dropdown/dropdown.jsx
  src/inputs/dropdown/dropdown.scss
  src/inputs/dropdown/dropdownItem.jsx
  src/inputs/dropdown/index.js
  src/inputs/durationPicker/durationPicker.jsx
  src/inputs/index.js
  src/inputs/phoneInput/phoneInput.scss
  src/inputs/phoneInput/phoneInputCountryDropdown.jsx
  src/inputs/select/__test__/select.test.js
  src/inputs/timePicker/timePicker.jsx
  src/inputs/timePicker/timePicker.scss
  src/navigation/a/a.jsx
  src/style.scss
  src/surfaces/filtersDrawer/filtersDrawer.jsx
  src/surfaces/filtersRail/__test__/filtersRailRowComponent.test.js
Labels: enhancement

#262 [dev] PBI AB#36142 Update Events Central with Mobile Components - Overview Page
  docs/src/layout/page/demo/demo.jsx
  src/surfaces/filtersDrawer/filtersDrawer.jsx
  src/surfaces/filtersDrawer/filtersDrawerNestedTogglesValueLabel.jsx
Labels: enhancement, priority medium
