Repository saddlebackdev/react-cm-ui, pull requests merged in 2020-09, with the labels that each got.

#198 [dev] No PBI - Fourth Level Navigation Fix
  docs/src/app/navigation.jsx
  docs/src/app/navigationConstants.js
  docs/src/routes.jsx
Labels: bug, docs

#203 [dev] AB#33495 - ActionBar Gap Closures
  src/dataDisplay/icon/icon.jsx
  src/dataDisplay/icon/icon.scss
  src/inputs/button/button.jsx
  src/inputs/dropdownButton/dropdownButton.jsx
  src/inputs/dropdownMenu/dropdownMenu.jsx
  src/inputs/dropdownMenu/dropdownMenu.scss
Labels: enhancement

#195 [dev] PBI AB#33440 - Navigation Breadcrumbs/Tabs prototypes
  docs/package-lock.json
  docs/src/app/navigationConstants.js
  docs/src/inputs/dropdownButton/dropdownButton.jsx
  docs/src/navigation/breadcrumbs/breadcrumbsSample.jsx
  docs/src/navigation/breadcrumbs/breadcrumbsSampleDividerString.jsx
  docs/src/navigation/breadcrumbs/breadcrumbsSampleOnlyPreviousRoute.jsx
  docs/src/navigation/breadcrumbs/index.jsx
  docs/src/navigation/sectionalTabs/index.jsx
  docs/src/navigation/sectionalTabs/sectionalTabsSample.jsx
  docs/src/navigation/sectionalTabs/sectionalTabsSampleSelectedTabKey.jsx
  docs/src/navigation/sectionalTabs/sectionalTabsSampleWithContent.jsx
  jest.setup.js
  package-lock.json
  package.json
  src/global/constants.js
  src/index.js
  src/inputs/dropdown/dropdown.jsx
  src/inputs/dropdownButton/dropdownButton.jsx
  src/inputs/dropdownMenu/dropdownMenu.jsx
  src/inputs/dropdownMenu/dropdownMenu.scss
  src/inputs/dropdownMenu/dropdownMenuConstants.js
  src/navigation/breadcrumbs/__test__/breadcrumbs.test.js
  src/navigation/breadcrumbs/__test__/breadcrumbsMockups.js
  src/navigation/breadcrumbs/__test__/breadcrumbsUtils.test.js
  src/navigation/breadcrumbs/breadcrumbs.jsx
  src/navigation/breadcrumbs/breadcrumbsUtils.js
  src/navigation/breadcrumbs/index.js
  src/navigation/sectionalTabs/__test__/sectionalTab.test.js
  src/navigation/sectionalTabs/__test__/sectionalTabContent.test.js
  src/navigation/sectionalTabs/__test__/sectionalTabs.test.js
  src/navigation/sectionalTabs/__test__/sectionalTabsMockUps.js
  src/navigation/sectionalTabs/index.js
  src/navigation/sectionalTabs/sectionalTab.jsx
  src/navigation/sectionalTabs/sectionalTabContent.jsx
  src/navigation/sectionalTabs/sectionalTabs.jsx
  src/style.scss
  src/versions.js
Labels: docs, enhancement, priority medium

#206 [dev] No PBI - Fixed Input Outlines
  .gitignore
  docs/src/dataDisplay/icon/iconExamples.jsx
  src/dataDisplay/icon/icon.jsx
  src/dataDisplay/icon/icon.scss
  src/inputs/button/button.jsx
Labels: bug

#207 [dev] AB#35112 - Radio Updates and ID Fix
  docs/src/inputs/radio/radio.jsx
  src/inputs/radio/radio.jsx
  src/inputs/radio/radio.scss
  src/inputs/radio/radioItem.jsx
  src/style.scss
Labels: bug, enhancement

#208 [dev] AB#33495 - New Select Component
  src/global/constants.js
  src/index.js
  src/inputs/index.js
  src/inputs/select/index.js
  src/inputs/select/select.jsx
Labels: enhancement

#211 [dev] Bug AB#33296: [Person Add 2.0] - Child/Student Records in duplicate list is displaying incorrect age
  src/dataDisplay/personPanel/personPanelSummary.jsx
Labels: bug, priority medium

#212 [dev] BUG AB#36859 [Events] Recurring Events Not Working Correctly
  src/inputs/datePickerCalendar/datePickerCalendar.jsx
Labels: bug, priority high
