Repository saddlebackdev/react-cm-ui, pull requests merged in 2020-10, with the labels that each got.

#215 [release/9.16.3] AB#36724 - Copy Change
  src/dataDisplay/personCoreMilestones/personCoreMilestones.jsx
Labels: bug

#202 [feature/cumulative--10.0.0] AB#33495 - ActionBar Gap Closures
  docs/package-lock.json
  docs/package.json
  docs/src/app/navigationConstants.js
  docs/src/global/example.jsx
  docs/src/global/exampleFrame.jsx
  docs/src/global/exampleFramed.jsx
  docs/src/layout/container/container.jsx
  docs/src/layout/container/index.js
  docs/src/layout/containerDeprecated/containerDeprecated.jsx
  docs/src/layout/containerDeprecated/index.js
  docs/src/layout/content/content.jsx
  docs/src/layout/content/index.js
  docs/src/surfaces/actionBar/actionBar.jsx
  docs/src/surfaces/actionBar/actionBarBasicSearchMdSample.jsx
  docs/src/surfaces/actionBar/actionBarBasicSearchSmSample.jsx
  docs/src/surfaces/actionBar/actionBarMdSample.jsx
  docs/src/surfaces/actionBar/actionBarSmSample.jsx
  src/global/constants.js
  src/index.js
  src/inputs/input/input.jsx
  src/inputs/input/input.scss
  src/inputs/phoneInput/phoneInputCountryDropdownValue.jsx
  src/inputs/prompt/prompt.jsx
  src/layout/container/container.jsx
  src/layout/container/container.scss
  src/layout/container/containerActionBar.jsx
  src/layout/container/containerContent.jsx
  src/layout/content/content.jsx
  src/layout/content/index.js
  src/layout/index.js
  src/layout/page/pageActionBar.jsx
  src/layout/page/pageContainer.jsx
  src/layout/page/pageContent.jsx
  src/style.scss
  src/styles/StylesProvider.js
  src/styles/index.js
  src/styles/jssPreset.js
  src/styles/theme.js
  src/surfaces/actionBar/__test__/actionBar.test.js
  src/surfaces/actionBar/__test__/actionBarActionsButton.test.js
  src/surfaces/actionBar/__test__/actionBarActionsButtonDrawerOption.test.js
  src/surfaces/actionBar/__test__/actionBarActionsButtonDrawerSubOption.test.js
  src/surfaces/actionBar/__test__/actionBarGridColumns.test.js
  src/surfaces/actionBar/__test__/actionBarSearch.test.js
  src/surfaces/actionBar/actionBar.jsx
  src/surfaces/actionBar/actionBar.scss
  src/surfaces/actionBar/actionBarActionsButton.jsx
  src/surfaces/actionBar/actionBarActionsButtonDrawerOption.jsx
  src/surfaces/actionBar/actionBarActionsButtonDrawerSubOption.jsx
  src/surfaces/actionBar/actionBarConstants.js
  src/surfaces/actionBar/actionBarGridColumns.jsx
  src/surfaces/actionBar/actionBarSearch.jsx
  src/surfaces/drawer/drawer.jsx
  src/surfaces/drawer/drawerContainer.jsx
  src/surfaces/drawer/drawerContent.jsx
  src/versions.js
Labels: enhancement

#217 [dev] [No Bug/PBI] Stop Propagation on click of <DropdownButton />
  src/inputs/dropdownButton/dropdownButton.jsx
Labels: enhancement, priority medium

#221 [dev] No PBI - Select Styling Fixes
  docs/package-lock.json
  src/inputs/select/select.jsx
Labels: bug

#223 [release/9.16.4] BUG AB#37522 - Fixed zIndexes
  docs/package-lock.json
  src/inputs/datePickerCalendar/datePickerCalendar.scss
  src/inputs/datePickerInput/datePickerInput.jsx
  src/inputs/datePickerInput/datePickerInput.scss
  src/inputs/prompt/prompt.jsx
  src/inputs/prompt/prompt.scss
  src/style.scss
  src/styles/theme.js
  src/surfaces/drawer/drawer.jsx
  src/surfaces/drawer/drawer.scss
  src/surfaces/drawerDeprecated/drawerDeprecated.jsx
  src/surfaces/drawerDeprecated/drawerDeprecated.scss
  src/surfaces/modal/modal.jsx
  src/surfaces/modal/modal.scss
  src/surfaces/modal/modalHeader.jsx
Labels: bug

#220 [feature/cumulative--10.0.0] AB#33495 - Filters Rail Gap Closures
  docs/src/global/example.jsx
  docs/src/global/exampleFrame.jsx
  docs/src/images/short_paul.jpg
  docs/src/surfaces/filtersRail/filtersRail.jsx
  docs/src/surfaces/filtersRail/filtersRailDrawerSample.jsx
  docs/src/surfaces/filtersRail/filtersRailPageSample.jsx
  package.json
  src/global/constants.js
  src/inputs/select/select.jsx
  src/navigation/a/a.jsx
  src/navigation/a/a.scss
  src/style.scss
  src/surfaces/actionBar/actionBar.jsx
  src/surfaces/drawer/drawer.scss
  src/surfaces/drawer/drawerFiltersDrawer.jsx
  src/surfaces/filtersRail/__test__/constants.js
  src/surfaces/filtersRail/__test__/filtersRail.test.js
  src/surfaces/filtersRail/__test__/filtersRailClear.test.js
  src/surfaces/filtersRail/__test__/filtersRailRow.test.js
  src/surfaces/filtersRail/__test__/filtersRailRowComponent.test.js
  src/surfaces/filtersRail/constants.js
  src/surfaces/filtersRail/filtersRail.jsx
  src/surfaces/filtersRail/filtersRail.scss
  src/surfaces/filtersRail/filtersRailClear.jsx
  src/surfaces/filtersRail/filtersRailRow.jsx
  src/surfaces/filtersRail/filtersRailRowComponent.jsx
  src/surfaces/rail/rail.jsx
  src/surfaces/rail/rail.scss
  src/testUtils/enzymeHelpers.jsx
  src/utils/index.js
  src/utils/slide/index.js
  src/utils/slide/slide.jsx
Labels: bug, enhancement

#225 [dev] Bug AB#33296: [Person Add 2.0] - Child/Student Records in duplicate list is displaying incorrect age
  src/dataDisplay/personPanel/personPanelSummary.jsx
Labels: bug

#224 [features/cumulative-followups-2.0] AB#32340 - [T.2] - Ability to add an action to a rule – Email – create new [DropdownButton bug fix]
  src/inputs/dropdownButton/dropdownButton.jsx
  src/inputs/dropdownMenu/dropdownMenu.jsx
Labels: bug, priority medium

#226 [features/cumulative-follow-ups-2.0] [PBI] AB#32340 - [T.2] - Ability to add an action to a rule – Email – create new [Select bug fix]
  src/inputs/select/select.jsx
Labels: bug

#229 [dev] No PBI - Fixed Popover Warnings
  src/dataDisplay/personCoreMilestones/personCoreMilestones.jsx
  src/dataDisplay/popover/popover.jsx
Labels: bug
