Repository saddlebackdev/react-cm-ui, pull requests merged in 2020-06, with the labels that each got.

#153 [dev] [No PBI] Fix image paths for deployed CM UI Docs website
  docs/src/app/navigation.jsx
  docs/src/dataDisplay/iconSet.jsx
  docs/src/dataDisplay/iconSubNavigation.jsx
  docs/src/dataDisplay/image.js
  docs/src/dataDisplay/image.jsx
  docs/src/inputs/dropdown.jsx
  docs/src/routes.jsx
  docs/template.ejs
Labels: bug

#156 [dev] AB#30853 - [My Events] - Custom fields drawer behind edit event drawer
  .eslintrc
  src/templates/drawer.jsx
  src/templates/drawerDeprecated.js
Labels: bug

#157 [dev] BUG AB#27358 [Events Central] - Please remove Phone from the Name column [drill through My Ministry tab]
  src/templates/dataGrid.jsx
  src/templates/dataGridTable.jsx
Labels: bug

#158 [dev] AB#24729 - Ability to perform a basic person search - [B.2]
  docs/src/templates/drawerSubNavigation.js
  docs/src/templates/pageSubNavigation.jsx
Labels: bug, priority medium

#161 [dev] No PBI - DropdownButton style fix and Button SCSS moved to JSS
  docs/src/index.jsx
  docs/src/inputs/dropdownButtonSubNavigation.jsx
  src/inputs/button.jsx
  src/inputs/button.scss
  src/inputs/buttonConstants.js
  src/inputs/dropdownButton.jsx
  src/style.scss
  src/styles/createPalette.js
  src/styles/shape.js
Labels: bug, enhancement, priority medium

#162 [dev] AB#24428 & AB#24723 - React-CM-UI Documentation Components
  .eslintrc
  docs/package-lock.json
  docs/package.json
  docs/src/global/componentApi.jsx
  docs/src/global/componentApiConstants.js
  docs/src/global/componentApiTable.jsx
  docs/src/global/example.jsx
  docs/src/global/heading.jsx
  docs/src/global/markdownContainer.jsx
  docs/src/global/tableProps.jsx
  src/colors/cyan.js
  src/colors/green.js
  src/colors/pink.js
  src/colors/redOrange.js
  src/colors/sky.js
  src/colors/teal.js
  src/global/constants.js
  src/index.js
  src/styles/breakpointsConstants.js
  src/styles/createTypography.js
  src/utils/index.js
  src/utils/useMediaQuery.js
Labels: priority high

#165 [dev] PBI AB#24730 Ability to perform a basic person search - [B.2] [mobile]
  src/styles/variables.scss
  src/templates/actionBar.scss
  src/templates/drawer.scss
  src/templates/drawerTitleBar.scss
Labels: bug

#147 [dev] AB#24428 - PersonPanel components
  docs/src/app/app.scss
  docs/src/app/navigationConstants.js
  docs/src/dataDisplay/personPanel.jsx
  docs/src/dataDisplay/personPanelConstants.js
  docs/src/dataDisplay/personPanelControlledAccordionExample.jsx
  docs/src/dataDisplay/personPanelCustomColumnsExample.jsx
  docs/src/dataDisplay/personPanelSimpleExample.jsx
  docs/src/global/images/andy_davis.jpg
  docs/src/global/images/princess_buttercup.jpg
  docs/src/global/images/princess_merida.jpg
  docs/src/global/images/the_dude.jpg
  docs/src/index.jsx
  docs/src/routes.jsx
  docs/src/templates/pageDemo.js
  src/colors/green.js
  src/dataDisplay/address.jsx
  src/dataDisplay/dataGroup.jsx
  src/dataDisplay/dataGroupExpandedRow.jsx
  src/dataDisplay/dataGroupRow.jsx
  src/dataDisplay/dataGroups.jsx
  src/dataDisplay/dataGroups.scss
  src/dataDisplay/dataGroupsColumn.jsx
  src/dataDisplay/dataGroupsPropTypes.js
  src/dataDisplay/emailLink.jsx
  src/dataDisplay/index.js
  src/dataDisplay/personCoreMilestones.jsx
  src/dataDisplay/personPanel.jsx
  src/dataDisplay/personPanelConstants.js
  src/dataDisplay/personPanelDetails.jsx
  src/dataDisplay/personPanelDetailsActionButton.jsx
  src/dataDisplay/personPanelSummary.jsx
  src/dataDisplay/personPanelSummaryContactText.jsx
  src/dataDisplay/telephoneLink.jsx
  src/index.js
  src/style.scss
  src/templates/drawerDataGroups.jsx
  src/templates/pageDataGroups.jsx
  src/utils/collapse.js
  src/utils/index.js
  src/utils/timeFromNow.jsx
  src/utils/withWidth.js
Labels: enhancement, priority high

#167 [dev] PBI AB#24730 - Ability to perform a basic person search - [B.2] [mobile]
  src/templates/actionBar.jsx
  src/templates/container.scss
  src/templates/content.scss
Labels: bug

#168 [dev] PBI AB#24730 - Ability to perform a basic person search - [B.2] [mobile]
  src/templates/actionBar.jsx
  src/templates/actionBarActionsButton.jsx
Labels: bug

#169 [dev] AB#27368 - Page gutters should be 44px at the desktop breakpoint (768px+)
  docs/src/routes.jsx
  docs/src/templates/pageDemo.jsx
  src/style.scss
  src/styles/theme.js
  src/templates/content.scss
  src/templates/dataCards.scss
  src/templates/dataGrid.scss
  src/templates/detailsWindow.scss
  src/templates/filtersRail.scss
  src/templates/page.jsx
  src/templates/page.scss
  src/templates/pageVariables.scss
Labels: bug, priority high

#170 [dev] Cleaned up Icon And Added Ability To Suppress Title
  src/dataDisplay/icon/icon.jsx
  src/dataDisplay/icon/iconConstants.js
  src/dataDisplay/icon/iconSVG.jsx
Labels: enhancement, priority medium

#163 [dev] - Deprecrated Disabled Prop and Added Disable Prop
  docs/src/dataDisplay/table/tableSampleDisabled.jsx
  docs/src/inputs/button.jsx
  docs/src/inputs/buttonDisableExample.jsx
  docs/src/inputs/checkbox.jsx
  docs/src/inputs/datePicker.jsx
  docs/src/inputs/datePickerInput.jsx
  docs/src/inputs/dropdown.jsx
  docs/src/inputs/durationPicker.jsx
  docs/src/inputs/input.jsx
  docs/src/inputs/phoneInput.jsx
  docs/src/inputs/radio.jsx
  docs/src/inputs/textArea.jsx
  docs/src/inputs/timePicker.jsx
  docs/src/templates/pageDemo.jsx
  src/dataDisplay/tableCell.jsx
  src/dataDisplay/tableRow.jsx
  src/inputs/button.jsx
  src/inputs/checkbox.jsx
  src/inputs/datePickerCalendarOnClickOutside.jsx
  src/inputs/datePickerInput.jsx
  src/inputs/durationPicker.jsx
  src/inputs/input.jsx
  src/inputs/phoneInput.jsx
  src/inputs/phoneInputCountryDropdown.jsx
  src/inputs/radio.jsx
  src/inputs/textArea.jsx
  src/templates/actionBarActionsButtonDrawerSubOption.jsx
  src/templates/filtersDrawer.jsx
Labels: bug, priority medium

#172 [release/9.13.0] - Splitter Icon Fix
  src/dataDisplay/icon/icon.jsx
  src/dataDisplay/icon/iconSVG.jsx
Labels: bug
