Repository saddlebackdev/react-cm-ui, pull requests merged in 2020-08, with the labels that each got.

#184 [dev] PBI AB#32635 Ability to create an event - When & Where - [E.1.2] - Recurring Event Re-Design
  src/inputs/radio.jsx
Labels: bug

#185 [dev] AB#33423 - Page Details Window Gutter Fix
  src/templates/detailsWindow.scss
Labels: bug

#189 [dev] Bug AB#33063: [Contact Information] Disable international region code for phone numbers
  src/inputs/phoneInput/phoneInputCountryDropdown.jsx
Labels: bug, priority medium

#193 [release/9.15.1] Bug AB#33063 Fix international option of country options
  src/inputs/phoneInput/phoneInput.jsx
  src/inputs/phoneInput/phoneInputCountryDropdown.jsx
  src/inputs/phoneInput/phoneInputCountryDropdownItem.jsx
  src/inputs/phoneInput/phoneInputCountryDropdownValue.jsx
Labels: bug, priority high

#192 [dev] Documentation Components & DataGrid JSS
  docs/package-lock.json
  docs/package.json
  docs/src/dataDisplay/dataGrid/dataGrid.jsx
  docs/src/dataDisplay/dataGrid/dataGridSample.jsx
  docs/src/dataDisplay/dataGrid/dataGridSortableRowsSample.jsx
  docs/src/dataDisplay/dataGrid/dataGridStickyColumnsSample.jsx
  docs/src/global/componentVersionIdentifier.jsx
  docs/src/global/example.jsx
  docs/src/inputs/radio/radio.jsx
  docs/src/surfaces/actionBar/actionBar.jsx
  src/dataDisplay/dataGrid/dataGrid.jsx
  src/dataDisplay/dataGrid/dataGrid.scss
  src/dataDisplay/dataGrid/dataGridTable.jsx
  src/dataDisplay/dataGrid/dataGridTableRow.jsx
  src/dataDisplay/personContactInfo/__test__/personContactInfo.test.js
  src/dataDisplay/personCoreMilestones/__test__/personCoreMilestones.test.js
  src/dataDisplay/personPanel/__test__/personPanel.test.js
  src/dataDisplay/personPanel/__test__/personPanelDetails.test.js
  src/dataDisplay/personPanel/__test__/personPanelDetailsActionButton.test.js
  src/dataDisplay/personPanel/__test__/personPanelSummary.test.js
  src/global/constants.js
  src/style.scss
  src/styles/theme.js
  src/testUtils/enzymeHelpers.jsx
  src/testUtils/mockedTheme.jsx
Labels: priority high

#197 [hotfix/9.15.2] fix: add missing `px` to JSS style rules on `<PageContent>`
  package-lock.json
  src/layout/page/pageContent.jsx
Labels: bug, priority high

#191 [cumulative] AB#33546 - Closed Grid Gaps
  docs/src/app/home.jsx
  docs/src/dataDisplay/dataGrid/dataGrid.jsx
  docs/src/dataDisplay/icon/icon.jsx
  docs/src/dataDisplay/table/tableSampleRowWithDragAndDrop.jsx
  docs/src/global/example.jsx
  docs/src/inputs/datePickerInput/datePickerInput.jsx
  docs/src/inputs/dropdownDeprecated/dropdownDeprecated.jsx
  docs/src/layout/grid/grid.jsx
  docs/src/layout/grid/gridAutoLayoutSample.jsx
  docs/src/layout/grid/gridBreakpointsSample.jsx
  docs/src/layout/grid/gridInteractive.jsx
  docs/src/layout/grid/gridNestedGridSample.jsx
  docs/src/layout/grid/gridSample.jsx
  docs/src/styleGuide/colors.jsx
  docs/src/surfaces/actionBar/actionBar.jsx
  docs/src/surfaces/actionBar/actionBarSample.jsx
  docs/src/surfaces/card/card.jsx
  src/dataDisplay/dataGrid/dataGridTableRow.jsx
  src/dataDisplay/personCoreMilestones/personCoreMilestones.jsx
  src/dataDisplay/personPanel/personPanelSummary.jsx
  src/global/constants.js
  src/inputs/datePickerDeprecated/datePickerDeprecatedCalendar.jsx
  src/inputs/datePickerDeprecated/datePickerDeprecatedInput.jsx
  src/layout/grid/__test__/grid.test.js
  src/layout/grid/__test__/gridColumn.test.js
  src/layout/grid/grid.jsx
  src/layout/grid/gridColumn.jsx
  src/layout/grid/gridConstants.js
  src/layout/grid/gridRow.jsx
  src/layout/page/pageActionBar.jsx
  src/style.scss
  src/surfaces/actionBar/actionBar.jsx
  src/surfaces/card/card.jsx
  src/surfaces/card/card.scss
  src/surfaces/card/cardHeader.jsx
  src/surfaces/drawer/drawerActionBar.jsx
  src/versions.js
Labels: enhancement, priority low

#194 [dev] PBI AB#34262 / Task AB#33950 Updated <DurationPicker> component
  docs/package-lock.json
  docs/package.json
  docs/src/dataDisplay/dataGrid/dataGrid.jsx
  docs/src/global/componentVersionIdentifier.jsx
  docs/src/inputs/durationPicker/durationPicker.jsx
  docs/src/inputs/durationPicker/durationPickerDaysHoursMinutesSecondsExample.jsx
  docs/src/inputs/durationPicker/durationPickerDisabledExample.jsx
  docs/src/inputs/durationPicker/durationPickerErrorHandlingExample.jsx
  docs/src/inputs/durationPicker/durationPickerLabelExample.jsx
  docs/src/inputs/durationPicker/durationPickerRequiredExample.jsx
  docs/src/inputs/durationPicker/durationPickerSimpleExample.jsx
  docs/src/inputs/durationPicker/durationPickerYearsMonthsDaysExample.jsx
  package.json
  src/inputs/durationPicker/__test__/durationPicker.test.js
  src/inputs/durationPicker/constants.js
  src/inputs/durationPicker/durationPicker.jsx
  src/inputs/durationPicker/durationPicker.scss
  src/style.scss
  src/versions.js
Labels: enhancement, priority medium
