Repository saddlebackdev/react-cm-ui, pull requests merged in 2020-07, with the labels that each got.

#174 [dev] Checkbox Bug Fix
  src/inputs/checkbox.jsx
Labels: bug

#160 [dev] AB#31150 - Eslint Fixes
  docs/src/app/header.js
  docs/src/app/header.jsx
  docs/src/app/styleGuideColors.js
  docs/src/app/styleGuideColors.jsx
  docs/src/atoms/header.js
  docs/src/atoms/label.js
  docs/src/atoms/loader.js
  docs/src/dataDisplay/banner.js
  docs/src/dataDisplay/divider.js
  docs/src/dataDisplay/iconExamples.js
  docs/src/dataDisplay/list.js
  docs/src/global/block.js
  docs/src/global/breakpointActions.js
  docs/src/global/breakpointReducer.js
  docs/src/global/configureReduxStore.js
  docs/src/global/swatch.js
  docs/src/molecules/comment.js
  docs/src/organisms/accordion.js
  docs/src/organisms/card.js
  docs/src/organisms/grid.js
  docs/src/organisms/infoBar.js
  docs/src/organisms/subNavigation.js
  docs/src/organisms/tabs.js
  docs/src/organisms/titleBar.js
  docs/src/reducers.js
  docs/src/routes.jsx
  docs/src/templates/drawer.js
  docs/src/templates/drawerActionBar.js
  docs/src/templates/drawerContent.js
  docs/src/templates/drawerDataGroups.js
  docs/src/templates/drawerDeprecated.js
  docs/src/templates/drawerDeprecatedFiltersDrawer.js
  docs/src/templates/drawerDetailsWindow.js
  docs/src/templates/drawerNavigation.js
  docs/src/templates/drawerSticky.js
  docs/src/templates/drawerTitleBar.js
  docs/src/templates/drawerWing.js
  docs/src/templates/modal.js
  docs/src/templates/subNavigation.js
  src/atoms/label.js
  src/atoms/label.jsx
  src/atoms/loader.js
  src/molecules/comment.js
  src/organisms/accordion.js
  src/organisms/container.js
  src/organisms/containerActionBar.js
  src/organisms/containerContent.js
  src/organisms/rail.js
  src/organisms/subNavigation.js
  src/organisms/subNavigationItem.js
  src/organisms/tabs.js
  src/organisms/tabsItem.js
  src/organisms/titleBar.js
  src/templates/modal.js
Labels: priority low

#175 [dev] AB#24428 - Added Classes and ID Props to PersonPanel Components
  src/dataDisplay/personPanel/__test__/personPanel.test.js
  src/dataDisplay/personPanel/__test__/personPanelDetails.test.js
  src/dataDisplay/personPanel/__test__/personPanelSummary.test.js
  src/dataDisplay/personPanel/personPanel.jsx
  src/dataDisplay/personPanel/personPanelDetails.jsx
  src/dataDisplay/personPanel/personPanelSummary.jsx
Labels: bug

#179 [dev] AB#32766 - Sticky table behavior not working after some unexpected library merges
  src/dataDisplay/table.jsx
  src/dataDisplay/tableHeaderCell.jsx
Labels: bug, priority medium

#181 [dev] AB#31102 - Modal/Prompt changes to match note reminders designs
  docs/src/inputs/prompt.jsx
  docs/src/templates/modal.js
  src/inputs/prompt.jsx
  src/inputs/prompt.scss
  src/inputs/textArea.jsx
  src/templates/modal.js
Labels: docs, enhancement, priority high

#180 [dev] AB#27438 - DataGrid Sortable Prop
  package-lock.json
  package.json
  src/dataDisplay/tableBody.jsx
  src/dataDisplay/tableCell.scss
  src/dataDisplay/tableRow.jsx
  src/templates/dataGrid.jsx
  src/templates/dataGrid.scss
  src/templates/dataGridConstants.js
  src/templates/dataGridTable.jsx
  src/templates/dataGridTableReactSortable.jsx
  src/templates/dataGridTableRow.jsx
  src/templates/drawerDataGrid.jsx
  src/templates/page.jsx
  src/templates/pageDataGrid.jsx
Labels: priority high
