Repository saddlebackdev/react-cm-ui, pull requests merged in 2020-11, with the labels that each got.

#228 [dev] AB#36901 AB#33546 - Filters Rail and Other Misc. Component Updates
  docs/src/app/navigationConstants.js
  docs/src/layout/page/demo/demo.jsx
  docs/src/layout/page/demo/demoFiltersRail.jsx
  docs/src/layout/page/demo/index.js
  docs/src/surfaces/filtersRail/filtersRail.jsx
  package.json
  src/global/constants.js
  src/index.js
  src/layout/container/container.jsx
  src/layout/container/container.scss
  src/layout/container/containerActionBar.jsx
  src/layout/container/containerContent.jsx
  src/layout/containerDeprecated/containerDeprecated.jsx
  src/layout/containerDeprecated/containerDeprecatedActionBar.jsx
  src/layout/containerDeprecated/containerDeprecatedContent.jsx
  src/layout/containerDeprecated/index.js
  src/layout/content/content.jsx
  src/layout/content/index.js
  src/layout/index.js
  src/layout/page/pageActionBar.jsx
  src/layout/page/pageContainer.jsx
  src/layout/page/pageContent.jsx
  src/style.scss
  src/styles/theme.js
  src/surfaces/filtersRail/__test__/constants.js
  src/surfaces/filtersRail/__test__/filtersRail.test.js
  src/surfaces/filtersRail/constants.js
  src/surfaces/filtersRail/filtersRail.jsx
  src/surfaces/rail/rail.jsx
  src/surfaces/rail/rail.scss
  src/testUtils/enzymeHelpers.jsx
  src/utils/domUtils.js
  src/utils/index.js
  src/utils/slide/index.js
  src/utils/slide/slide.jsx
Labels: bug, enhancement, priority high

#236 [dev] PBI AB#39258 [Events] Create Dynamic Start/End time dropdown UI
  src/inputs/dropdown/dropdown.jsx
Labels: priority high

#237 [feature/cumulative--10.0.0] AB#33500 - Close Inputs gap between Sketch Cloud and cm-ui library
  docs/src/app/navigationConstants.js
  docs/src/inputs/prompt/api/api.jsx
  docs/src/inputs/prompt/api/index.js
  docs/src/inputs/prompt/devSandbox/devSandbox.jsx
  docs/src/inputs/prompt/devSandbox/index.js
  docs/src/inputs/prompt/examples/exampleAlertPrompt.jsx
  docs/src/inputs/prompt/examples/exampleDefaultPrompt.jsx
  docs/src/inputs/prompt/examples/exampleDropdownButtonPrompt.jsx
  docs/src/inputs/prompt/examples/exampleInformativePrompt.jsx
  docs/src/inputs/prompt/examples/exampleSuccessPrompt.jsx
  docs/src/inputs/prompt/examples/exampleWarningPrompt.jsx
  docs/src/inputs/prompt/prompt.jsx
  src/inputs/prompt/__test__/prompt.test.js
  src/inputs/prompt/prompt.jsx
  src/inputs/prompt/prompt.scss
  src/style.scss
Labels: docs, enhancement

#238 [feature/cumulative--10.0.0] AB#33500 Icon Gap
  docs/src/dataDisplay/icon/icon.jsx
  src/dataDisplay/icon/icon.jsx
Labels: enhancement

#235 [feature/10.0.0--button] AB#33500 - Closed Radio Gap
  docs/package-lock.json
  docs/src/app/navigationConstants.js
  docs/src/inputs/radio/api/api.jsx
  docs/src/inputs/radio/api/index.js
  docs/src/inputs/radio/devSandbox/devSandbox.jsx
  docs/src/inputs/radio/devSandbox/examples/exampleAlign.jsx
  docs/src/inputs/radio/devSandbox/examples/exampleChecked.jsx
  docs/src/inputs/radio/devSandbox/examples/exampleDisable.jsx
  docs/src/inputs/radio/devSandbox/examples/exampleFluid.jsx
  docs/src/inputs/radio/devSandbox/examples/exampleGroup.jsx
  docs/src/inputs/radio/devSandbox/examples/exampleLabel.jsx
  docs/src/inputs/radio/devSandbox/examples/exampleLabelClick.jsx
  docs/src/inputs/radio/devSandbox/examples/exampleOnChange.jsx
  docs/src/inputs/radio/devSandbox/examples/examplePill.jsx
  docs/src/inputs/radio/devSandbox/examples/examplePillDisable.jsx
  docs/src/inputs/radio/devSandbox/examples/examplePillMulti.jsx
  docs/src/inputs/radio/devSandbox/examples/exampleStandard.jsx
  docs/src/inputs/radio/devSandbox/index.js
  docs/src/inputs/radio/examples/radioSample.jsx
  docs/src/inputs/radio/examples/radioSamplePill.jsx
  docs/src/inputs/radio/radio.jsx
  src/global/constants.js
  src/inputs/radio/__test__/radio.test.js
  src/inputs/radio/radio.jsx
  src/inputs/radio/radioItem.jsx
Labels: enhancement, priority high

#241 [dev] No AB - Container Deprecated Styling Fixes
  src/layout/containerDeprecated/containerDeprecated.jsx
  src/layout/containerDeprecated/containerDeprecatedActionBar.jsx
  src/surfaces/filtersRail/filtersRail.jsx
Labels: bug

#239 [feature/cululative--10.0.0] AB#33496 - Removed Loader Component
  docs/src/app/navigationConstants.js
  docs/src/feedback/loader/index.js
  docs/src/feedback/loader/loader.jsx
  src/feedback/index.js
  src/feedback/loader/index.js
  src/feedback/loader/loader.jsx
  src/feedback/loader/loader.scss
  src/index.js
  src/style.scss
Labels: enhancement

#240 [feature/cumulative--10.0.0] AB#33546 - Removed Container Deprecated
  src/index.js
  src/layout/containerDeprecated/containerDeprecated.jsx
  src/layout/containerDeprecated/containerDeprecatedActionBar.jsx
  src/layout/containerDeprecated/containerDeprecatedContent.jsx
  src/layout/containerDeprecated/index.js
  src/layout/index.js
Labels: enhancement

#245 [feature/cumulative--10.0.0] AB#33499 - Banner Component
  docs/src/app/navigationConstants.js
  docs/src/dataDisplay/banner/api/api.jsx
  docs/src/dataDisplay/banner/api/index.js
  docs/src/dataDisplay/banner/banner.jsx
  docs/src/dataDisplay/banner/devSandbox/devSandbox.jsx
  docs/src/dataDisplay/banner/devSandbox/index.js
  docs/src/dataDisplay/banner/examples/exampleAlertBanner.jsx
  docs/src/dataDisplay/banner/examples/exampleConfirmingBanner.jsx
  docs/src/dataDisplay/banner/examples/exampleDefaultBanner.jsx
  docs/src/dataDisplay/banner/examples/exampleInformativeBanner.jsx
  docs/src/dataDisplay/banner/examples/exampleOnAfterCloseBanner.jsx
  docs/src/dataDisplay/banner/examples/exampleStandardBanner.jsx
  docs/src/dataDisplay/banner/examples/exampleWarningBanner.jsx
  src/dataDisplay/banner/__test__/banner.test.js
  src/dataDisplay/banner/banner.jsx
  src/dataDisplay/banner/banner.scss
  src/dataDisplay/banner/bannerItem.jsx
  src/style.scss
  src/styles/createPalette.js
Labels: docs, enhancement
