Repository saddlebackdev/react-cm-ui, pull requests merged in 2021-04, with the labels that each got.

#277 [dev] No PBI - Enhancing Person Panel Select Record button for Client's Add Person V2
  src/dataDisplay/personPanel/__test__/personPanelDetails.test.js
  src/dataDisplay/personPanel/personPanelDetails.jsx
  src/dataDisplay/personPanel/personPanelDetailsActionButton.jsx
Labels: enhancement, priority high

#279 [dev] No PBI - PersonCoreMilestones and Popover Improvements
  docs/src/app/app.scss
  docs/src/app/header.scss
  docs/src/app/home.scss
  docs/src/app/navigationConstants.js
  docs/src/app/tabs.jsx
  docs/src/dataDisplay/personCoreMilestones/api/api.jsx
  docs/src/dataDisplay/personCoreMilestones/api/index.js
  docs/src/dataDisplay/personCoreMilestones/examples/exampleAdultFemale.jsx
  docs/src/dataDisplay/personCoreMilestones/examples/exampleAdultMale.jsx
  docs/src/dataDisplay/personCoreMilestones/examples/exampleChild.jsx
  docs/src/dataDisplay/personCoreMilestones/examples/exampleDisable.jsx
  docs/src/dataDisplay/personCoreMilestones/examples/exampleStudent.jsx
  docs/src/dataDisplay/personCoreMilestones/examples/exampleUndefined.jsx
  docs/src/dataDisplay/personCoreMilestones/personCoreMilestones.jsx
  docs/src/global/Block.scss
  docs/src/global/Highlighter.scss
  docs/src/global/Swatch.scss
  docs/src/global/TableProps.scss
  docs/src/global/block.js
  docs/src/global/block.jsx
  docs/src/global/main.scss
  docs/src/global/swatch.js
  docs/src/global/swatch.jsx
  src/dataDisplay/personCoreMilestones/__test__/personCoreMilestones.test.js
  src/dataDisplay/personCoreMilestones/constants.js
  src/dataDisplay/personCoreMilestones/gridColumnAcceptedChrist.jsx
  src/dataDisplay/personCoreMilestones/gridColumnBaptised.jsx
  src/dataDisplay/personCoreMilestones/gridColumnClassBaseballDiamond.jsx
  src/dataDisplay/personCoreMilestones/gridColumnMinistry.jsx
  src/dataDisplay/personCoreMilestones/gridColumnMissions.jsx
  src/dataDisplay/personCoreMilestones/gridColumnSmallGroup.jsx
  src/dataDisplay/personCoreMilestones/milestonePopoverContent.jsx
  src/dataDisplay/personCoreMilestones/personCoreMilestones.jsx
  src/dataDisplay/personCoreMilestones/utils.js
  src/dataDisplay/personPanel/personPanelDetails.jsx
  src/dataDisplay/popover/__test__/popover.test.js
  src/dataDisplay/popover/popover.jsx
  src/navigation/sectionalTabs/sectionalTabs.jsx
  src/surfaces/appBar/appBar.jsx
Labels: bug, enhancement, priority high

#278 [dev] BUG AB#45246 [Events Central][Mobile] - Tapping on [ x ] icon next to the campus name does not remove it from the filters
  src/surfaces/filtersDrawer/filtersDrawerMultiSelectLabel.jsx
Labels: bug

#281 [hotfix/9.21.0-hotfix] Bug AB#46500, AB#46499 - Person Core Milestone Style Fix and CLASS Became A Member Fix.
  src/dataDisplay/personCoreMilestones/gridColumnAcceptedChrist.jsx
  src/dataDisplay/personCoreMilestones/gridColumnBaptised.jsx
  src/dataDisplay/personCoreMilestones/gridColumnClassBaseballDiamond.jsx
  src/dataDisplay/personCoreMilestones/gridColumnMinistry.jsx
  src/dataDisplay/personCoreMilestones/gridColumnMissions.jsx
  src/dataDisplay/personCoreMilestones/gridColumnSmallGroup.jsx
  src/dataDisplay/personCoreMilestones/personCoreMilestones.jsx
Labels: bug, priority high
