Repository saddlebackdev/react-cm-ui, pull requests merged in 2021-06, with the labels that each got.

#300 [dev] AB#35036 [Follow Ups > Sort and Filter][B.2] - Campus list is not aligned properly when you open the dropdown
  docs/src/layout/page/demo/demo.jsx
  docs/src/layout/page/demo/demoFiltersRail.jsx
  src/layout/page/pageFiltersRail.jsx
  src/surfaces/drawer/drawerFiltersRail.jsx
  src/surfaces/filtersRail/filtersRail.jsx
Labels: bug, priority high

#302 [hotfix/10.0.3] Bug AB#48126: [Serving Opportunities] - Scroll Down is not working on HC (intermittent problem)
  src/surfaces/modal/modal.jsx
Labels: bug, priority high

#304 [dev] AB#48476: [G.1.1] - Ability to quick create multiple serving opportunities (one-time event)
  src/dataDisplay/dataCards/dataCards.jsx
  src/dataDisplay/dataGrid/dataGrid.jsx
  src/dataDisplay/dataGroups/dataGroups.jsx
  src/surfaces/drawer/drawerActionBar.jsx
  src/surfaces/drawer/drawerContainer.jsx
  src/surfaces/drawer/drawerContent.jsx
  src/surfaces/drawer/drawerDataCards.jsx
  src/surfaces/drawer/drawerDataGrid.jsx
  src/surfaces/drawer/drawerDataGroups.jsx
  src/surfaces/drawer/drawerDetailsWindow.jsx
  src/surfaces/drawer/drawerFiltersDrawer.jsx
  src/surfaces/drawer/drawerFiltersRail.jsx
  src/surfaces/drawer/drawerNavigation.jsx
  src/surfaces/drawer/drawerTitleBar.jsx
  src/surfaces/drawer/drawerWing.jsx
Labels: enhancement

#305 [dev] AB#48476: [G.1.1] - Ability to quick create multiple serving opportunities (one-time event)
  src/layout/page/pageActionBar.jsx
  src/surfaces/actionBar/actionBar.jsx
  src/surfaces/drawer/drawerActionBar.jsx
Labels: enhancement, risk: low

#306 [dev] AB#48476: [G.1.1] - Ability to quick create multiple serving opportunities (one-time event)
  src/layout/grid/grid.jsx
  src/layout/grid/gridColumn.jsx
Labels: enhancement

#307 [release/10.0.3-hotfix] AB#47299: [Events > Check-in] [UI] - Person Relationship records are Not Scrolling horizontally & Broken display of Person record After you adjust Zoom
  src/surfaces/drawer/drawer.jsx
Labels: bug, priority: high, risk: low

#310 [dev] (Snackbar and Palette Gap Closure) AB#48476: [G.1.1] - Ability to quick create multiple serving opportunities (one-time event)
  docs/src/app/navigationConstants.js
  docs/src/feedback/snackbar/api/api.jsx
  docs/src/feedback/snackbar/api/index.js
  docs/src/feedback/snackbar/examples/exampleSnackbar.jsx
  docs/src/feedback/snackbar/index.js
  docs/src/feedback/snackbar/snackbar.jsx
  src/feedback/index.js
  src/feedback/snackbar/__test__/snackbar.test.js
  src/feedback/snackbar/index.js
  src/feedback/snackbar/snackbar.jsx
  src/global/constants.js
  src/index.js
  src/inputs/dropdownMenu/dropdownMenu.jsx
  src/styles/createPalette.js
Labels: enhancement, priority: high

#311 [dev] (Fade) AB#48476: [G.1.1] - Ability to quick create multiple serving opportunities (one-time event)
  src/index.js
  src/utils/fade/fade.jsx
  src/utils/fade/index.js
  src/utils/index.js
Labels: enhancement, priority: high

#303 [dev] (Icon Gap Closure) AB#46100: [A.1] - Ability to upload a web header
  docs/src/app/navigationConstants.js
  docs/src/dataDisplay/icon/api/api.jsx
  docs/src/dataDisplay/icon/api/index.js
  docs/src/dataDisplay/icon/icon.jsx
  docs/src/dataDisplay/icon/iconExamples.jsx
  src/dataDisplay/icon/icon.jsx
  src/global/constants.js
Labels: enhancement, priority: low, risk: medium

#309 [dev] (Select Gap Closure) AB#48476: [G.1.1] - Ability to quick create multiple serving opportunities (one-time event)
  docs/src/app/navigationConstants.js
  docs/src/inputs/select/api/api.jsx
  docs/src/inputs/select/api/index.js
  docs/src/inputs/select/constants.js
  docs/src/inputs/select/devSandbox/devSandbox.jsx
  docs/src/inputs/select/devSandbox/index.js
  docs/src/inputs/select/examples/exampleClearableSelect.jsx
  docs/src/inputs/select/examples/exampleCreatableAdvancedSelect.jsx
  docs/src/inputs/select/examples/exampleCreatableSelect.jsx
  docs/src/inputs/select/examples/exampleDefaultSelect.jsx
  docs/src/inputs/select/examples/exampleDisableSelect.jsx
  docs/src/inputs/select/examples/exampleLabelSelect.jsx
  docs/src/inputs/select/examples/exampleMultipleSelect.jsx
  docs/src/inputs/select/examples/exampleRequiredSelect.jsx
  docs/src/inputs/select/examples/exampleSearchableSelect.jsx
  docs/src/inputs/select/index.js
  docs/src/inputs/select/select.jsx
  src/inputs/select/select.jsx
Labels: bug, enhancement, priority: high
