Repository saddlebackdev/react-cm-ui, pull requests merged in 2021-07, with the labels that each got.

#312 [dev] AB#48476: [G.1.1] - Ability to quick create multiple serving opportunities (one-time event)
  src/feedback/snackbar/snackbar.jsx
Labels: bug

#314 [dev] PBI AB#49205 [BG.1.1] Ability to check in an attendee - select existing person record (relationship exists) (child check-in)
  src/surfaces/actionBar/actionBar.jsx
  src/surfaces/actionBar/actionBarSearch.jsx
Labels: enhancement, priority: medium, risk: low

#313 [dev] Typography Updates
  docs/src/styleGuide/typography.jsx
  docs/src/styleGuide/typographyGridColumn.jsx
  src/styles/createTypography.js
Labels: enhancement

#316 [dev] AB#48476: [G.1.1] - Ability to quick create multiple serving opportunities (one-time event)
  src/inputs/prompt/prompt.jsx
Labels: enhancement

#315 [dev] AB#48476: [G.1.1] - Ability to quick create multiple serving opportunities (one-time event)
  docs/src/inputs/dropdownDeprecated/dropdownDeprecated.jsx
  docs/src/inputs/select/constants.js
  docs/src/inputs/select/examples/exampleDefaultSelect.jsx
  src/inputs/select/select.jsx
Labels: bug, priority: high

#317 [dev] PBI AB#48476: Select `noResultsMessage` prop
  src/inputs/select/select.jsx
Labels: enhancement, priority: high, risk: low
