Repository saddlebackdev/react-cm-ui, pull requests merged in 2021-09, with the labels that each got.

#324 [dev] PBI AB#51574: Palette Update to support the DX-React-Scheduler-Material-UI package
  package.json
  src/styles/createPalette.js
Labels: enhancement

#328 [dev] [No Bug/PBI] Fix warning "[JSS] Cannot set property 'parentStyleSheet' of undefined"
  jest.setup.js
Labels: enhancement, priority: medium

#329 [dev] AB#25926 - [W.2] - Ability to create an entry for a connection form - Modification of default props on person panel react-cm-ui component
  src/dataDisplay/personPanel/personPanelDetails.jsx
  src/dataDisplay/personPanel/personPanelSummary.jsx
Labels: enhancement, priority: high, risk: medium

#327 [dev] AB#51574: List and Divider Updates
  src/dataDisplay/divider/constants.js
  src/dataDisplay/divider/divider.jsx
  src/dataDisplay/divider/dividerDeprecated.jsx
  src/dataDisplay/divider/dividerDeprecated.scss
  src/dataDisplay/index.js
  src/dataDisplay/list/constants.js
  src/dataDisplay/list/list.jsx
  src/dataDisplay/list/listDeprecated.jsx
  src/dataDisplay/list/listDeprecated.scss
  src/dataDisplay/list/listItemDeprecated.jsx
  src/dataDisplay/listItem/index.js
  src/dataDisplay/listItem/listItem.jsx
  src/dataDisplay/listItemAvatar/index.js
  src/dataDisplay/listItemAvatar/listItemAvatar.jsx
  src/dataDisplay/listItemIcon/index.js
  src/dataDisplay/listItemIcon/listItemIcon.jsx
  src/dataDisplay/listItemSecondaryAction/index.js
  src/dataDisplay/listItemSecondaryAction/listItemSecondaryAction.jsx
  src/dataDisplay/listItemText/index.js
  src/dataDisplay/listItemText/listItemText.jsx
  src/dataDisplay/listSubheader/index.js
  src/dataDisplay/listSubheader/listSubheader.jsx
  src/index.js
  src/style.scss
Labels: enhancement, WIP

#331 [dev] PBI AB#51691: Dropdown Button Enhancements and Fixes
  src/inputs/dropdownButton/dropdownButton.jsx
  src/inputs/dropdownMenu/dropdownMenu.jsx
  src/inputs/dropdownMenu/dropdownMenuDivider.jsx
  src/inputs/dropdownMenu/dropdownMenuHeading.jsx
  src/inputs/dropdownMenu/dropdownMenuOption.jsx
Labels: bug, enhancement
