Repository saddlebackdev/react-cm-ui, pull requests merged in 2021-11, with the labels that each got.

#336 [dev] Bug AB#56953: Replaced Droid Serif with Georgia To Help With Load Time
  src/styles/fonts.scss
  src/styles/typography.scss
Labels: enhancement

#337 [dev] No PBI - Fixing Image type prop (it was always rendering 'user').
  src/dataDisplay/image/image.jsx
Labels: bug, priority: medium, risk: high

#335 [dev] No PBI - Fixes Sectional Nav Indicator
  src/navigation/sectionalTabs/__test__/sectionalTabs.test.js
  src/navigation/sectionalTabs/constants.js
  src/navigation/sectionalTabs/sectionalTab.jsx
  src/navigation/sectionalTabs/sectionalTabs.jsx
Labels: bug, enhancement

#338 [dev] Bug AB#57694: [Person Record] Flags are not displayed on the drop down menu in the Phone Number field on Person Record 1.0
  src/inputs/phoneInput/phoneInput.jsx
Labels: bug, priority: high, risk: medium

#342 [hotfix/10.2.5] Bug 58770: [PS][Back Office] - All images receiving Person Avatar styling
  jest.setup.js
  package-lock.json
  package.json
  src/dataDisplay/icon/icon.jsx
  src/dataDisplay/image/__test__/image.test.js
  src/dataDisplay/image/image.jsx
  src/testUtils/index.js
  src/testUtils/testUtils.jsx
Labels: bug, priority: high, risk: medium

#340 [dev] PBI AB#58154: [Tech Debt] Add Box (MUI) To React-CM-UI
  docs/src/app/navigationConstants.js
  docs/src/layout/box/box.jsx
  docs/src/layout/box/examples/exampleBox.jsx
  docs/src/layout/box/index.js
  src/index.js
  src/layout/box/box.jsx
  src/layout/box/index.js
  src/layout/index.js
  src/versions.js
Labels: enhancement

#339 [dev] PBI AB#56716: [Tech Debt] Add MUI Timeline Components
  docs/src/app/navigationConstants.js
  docs/src/lab/timeline/examples/exampleTimeline.jsx
  docs/src/lab/timeline/index.js
  docs/src/lab/timeline/timeline.jsx
  src/feedback/activityIndicator/activityIndicator.jsx
  src/index.js
  src/lab/index.js
  src/lab/timeline/index.js
  src/lab/timeline/timeline.jsx
  src/lab/timelineConnector/index.js
  src/lab/timelineConnector/timelineConnector.jsx
  src/lab/timelineContent/index.js
  src/lab/timelineContent/timelineContent.jsx
  src/lab/timelineDot/index.js
  src/lab/timelineDot/timelineDot.jsx
  src/lab/timelineItem/index.js
  src/lab/timelineItem/timelineItem.jsx
  src/lab/timelineOppositeContent/index.js
  src/lab/timelineOppositeContent/timelineOppositeContent.jsx
  src/lab/timelineSeparator/index.js
  src/lab/timelineSeparator/timelineSeparator.jsx
  src/versions.js
Labels: enhancement
