Repository saddlebackdev/react-cm-ui, pull requests merged in 2022-02, with the labels that each got.

#354 [dev] [No Bug/PBI] Fix `data-testid` issue for `<DataGroups>`
  docs/src/layout/page/demo/demo.jsx
  src/dataDisplay/dataGroups/__test__/dataGroups.test.js
  src/dataDisplay/dataGroups/dataGroups.jsx
  src/surfaces/actionBar/actionBar.jsx
Labels: bug, enhancement, priority: medium, docs, risk: low

#353 [dev] AB#28687 - [System] - Warning message is not displaying a properly format
  docs/src/app/navigationConstants.js
  docs/src/inputs/input/api/api.jsx
  docs/src/inputs/input/api/index.js
  docs/src/inputs/input/devSandbox/devSandbox.jsx
  docs/src/inputs/input/devSandbox/index.js
  docs/src/inputs/input/examples/exampleDefaultInput.jsx
  docs/src/inputs/input/examples/exampleInputAutoFocus.jsx
  docs/src/inputs/input/examples/exampleInputAutocomplete.jsx
  docs/src/inputs/input/examples/exampleInputDisabled.jsx
  docs/src/inputs/input/examples/exampleInputError.jsx
  docs/src/inputs/input/examples/exampleInputErrorWithText.jsx
  docs/src/inputs/input/examples/exampleInputFluid.jsx
  docs/src/inputs/input/examples/exampleInputIcon.jsx
  docs/src/inputs/input/examples/exampleInputIconCustom.jsx
  docs/src/inputs/input/examples/exampleInputInverse.jsx
  docs/src/inputs/input/examples/exampleInputLabel.jsx
  docs/src/inputs/input/examples/exampleInputLabelPosition.jsx
  docs/src/inputs/input/examples/exampleInputLoading.jsx
  docs/src/inputs/input/examples/exampleInputMask.jsx
  docs/src/inputs/input/examples/exampleInputMaxLength.jsx
  docs/src/inputs/input/examples/exampleInputMaxMin.jsx
  docs/src/inputs/input/examples/exampleInputMinLength.jsx
  docs/src/inputs/input/examples/exampleInputOnBlur.jsx
  docs/src/inputs/input/examples/exampleInputOnChange.jsx
  docs/src/inputs/input/examples/exampleInputOnClick.jsx
  docs/src/inputs/input/examples/exampleInputOnFocus.jsx
  docs/src/inputs/input/examples/exampleInputOnKeyDown.jsx
  docs/src/inputs/input/examples/exampleInputPlaceholder.jsx
  docs/src/inputs/input/examples/exampleInputRequired.jsx
  docs/src/inputs/input/examples/exampleInputType.jsx
  docs/src/inputs/input/input.jsx
  src/global/constants.js
  src/inputs/input/input.jsx
Labels: enhancement, priority: medium, risk: medium

#356 [dev] PBIs AB#61450 AB#61451 AB#61455: ForwardedRefs, Button Type Prop, and Select Bug Fixes
  docs/src/inputs/input/examples/exampleDefaultInput.jsx
  docs/src/inputs/input/input.jsx
  src/inputs/button/button.jsx
  src/inputs/button/buttonConstants.js
  src/inputs/checkbox/checkbox.jsx
  src/inputs/datePickerInput/datePickerInput.jsx
  src/inputs/input/input.jsx
  src/inputs/select/select.jsx
  src/inputs/textArea/textArea.jsx
Labels: bug, enhancement, priority: high, risk: medium

#355 [dev] Bug AB#59185 [Mobile][My Ministries > Serving Opps] After adding a new Opportunity in My Ministry, the "Actions" pop out drawer does not close automatically | Extend Mobile Action Bar Actions Button and Actions Drawer to provide the option of toggling the Actions Drawer closed when an option is clicked
  src/surfaces/actionBar/actionBarActionsButton.jsx
  src/surfaces/actionBar/actionBarActionsButtonDrawerOption.jsx
  src/surfaces/actionBar/actionBarActionsButtonDrawerSubOption.jsx
Labels: enhancement, priority: medium, risk: low

#361 [dev] [No Bug/PBI] ESLINT is back baby!
  .eslintrc
  package-lock.json
  package.json
Labels: bug, enhancement, dependencies, priority: medium, risk: medium

#359 [dev] Bug AB#59185 [Mobile][My Ministries > Serving Opps] After adding a new Opportunity in My Ministry, the "Actions" pop out drawer does not close automatically | Extend Mobile Action Bar Actions Button and Actions Drawer to provide the option of toggling the Actions Drawer closed when an option is clicked
  src/surfaces/actionBar/actionBarActionsButtonDrawerOption.jsx
Labels: enhancement, priority: high, risk: medium
