Repository saddlebackdev/react-cm-ui, pull requests merged in 2022-06, with the labels that each got.

#378 [dev] No PBI - Button `disabled` Bug Fix
  src/inputs/button/button.jsx
  src/inputs/button/buttonConstants.js
Labels: bug, priority: medium, risk: medium

#379 [dev] PBI AB#72763: Added The Ability Have A Custom Gradient On An Icon
  .eslintrc
  docs/package-lock.json
  docs/package.json
  docs/src/app/navigationConstants.js
  docs/src/dataDisplay/icon/devSandbox/devSandbox.jsx
  docs/src/dataDisplay/icon/devSandbox/examples/exampleAlign.jsx
  docs/src/dataDisplay/icon/devSandbox/examples/exampleColor.jsx
  docs/src/dataDisplay/icon/devSandbox/examples/exampleCompact.jsx
  docs/src/dataDisplay/icon/devSandbox/examples/exampleGradient.jsx
  docs/src/dataDisplay/icon/devSandbox/examples/exampleInverseColor.jsx
  docs/src/dataDisplay/icon/devSandbox/examples/exampleOnClick.jsx
  docs/src/dataDisplay/icon/devSandbox/examples/exampleRotate.jsx
  docs/src/dataDisplay/icon/devSandbox/examples/exampleSize.jsx
  docs/src/dataDisplay/icon/devSandbox/examples/exampleSpin.jsx
  docs/src/dataDisplay/icon/devSandbox/examples/exampleStandard.jsx
  docs/src/dataDisplay/icon/devSandbox/examples/exampleTitle.jsx
  docs/src/dataDisplay/icon/devSandbox/index.js
  docs/src/dataDisplay/icon/iconExamples.jsx
  docs/tsconfig.json
  docs/webpack.config.js
  gulpfile.babel.js
  jest.config.js
  package-lock.json
  package.json
  src/dataDisplay/icon/icon.d.ts
  src/dataDisplay/icon/icon.jsx
  src/dataDisplay/icon/iconConstants.js
  src/dataDisplay/icon/models/colorType.model.ts
  src/dataDisplay/icon/models/index.ts
  src/inputs/dropdownButton/dropdownButton.jsx
Labels: priority: medium, risk: high

#380 [dev] No PBI - Added Button Types And Fixed Docs' Button API Page.
  src/inputs/button/button.d.ts
  src/inputs/button/button.jsx
  src/inputs/button/buttonConstants.js
  src/inputs/button/buttonDeprecated.jsx
  src/inputs/button/models/asType.model.ts
  src/inputs/button/models/buttonType.model.ts
  src/inputs/button/models/colorType.model.ts
  src/inputs/button/models/index.ts
  src/inputs/button/models/variantType.model.ts
  src/inputs/dropdownButton/dropdownButton.jsx
Labels: bug, priority: medium, risk: medium

#383 [dev] [No Bug/PBI] Fix `disabled` vs. `disable` in `<DropdownMenuOption />`
  src/inputs/dropdownMenu/dropdownMenuOption.jsx
Labels: enhancement, priority: medium, risk: low
