Repository saddlebackdev/react-cm-ui, pull requests merged in 2022-05, with the labels that each got.

#373 [dev] PBI 59401: tableRef Defensiveness
  src/dataDisplay/dataGrid/dataGridTable.jsx
  src/dataDisplay/table/table.jsx
Labels: priority: high, risk: medium

#374 [dev] Bug AB#72828: [Tech Debt] Quick Notification Drawer does not stay open
  src/surfaces/drawer/drawer.jsx
  src/surfaces/drawer/drawerTitleBar.jsx
Labels: bug, priority: high, risk: medium

#375 [dev] [No PBI] - Input fields ExampleInputMask not working correctly
  docs/src/inputs/input/examples/exampleInputMask.jsx
Labels: bug, priority: medium, docs, risk: low

#376 [dev] PBI AB#66009: Changed Drawer's `onClickOutside` prop to `shouldCloseOnClickOutside`
  .eslintrc
  src/surfaces/drawer/drawer.d.ts
  src/surfaces/drawer/drawer.jsx
Labels: bug, priority: high, risk: low
