Repository saddlebackdev/react-cm-ui, pull requests merged in 2022-03, with the labels that each got.

#365 [dev] PBI AB#59572: Removed Input's `showRequiredIndicator` component state
  .eslintrc
  src/inputs/input/input.jsx
Labels: bug, priority: medium, risk: medium

#362 [dev] [No Bug/PBI] Remove console warnings about use of `disabled` prop
  docs/src/inputs/button/api/api.jsx
  docs/src/inputs/button/button.jsx
  docs/src/inputs/dropdownButton/dropdownButton.jsx
  docs/src/routes.jsx
  src/dataDisplay/dataGroups/__test__/dataGroups.test.js
  src/dataDisplay/table/tableCell.jsx
  src/dataDisplay/table/tableRow.jsx
  src/inputs/button/button.jsx
  src/inputs/button/buttonConstants.js
  src/inputs/button/buttonDeprecated.jsx
  src/inputs/checkbox/checkbox.jsx
  src/inputs/datePickerCalendar/datePickerCalendar.jsx
  src/inputs/datePickerDeprecated/datePickerDeprecatedInput.jsx
  src/inputs/datePickerInput/__test__/datePickerInput.test.js
  src/inputs/datePickerInput/datePickerInput.jsx
  src/inputs/dropdownButton/dropdownButton.jsx
  src/inputs/durationPicker/durationPicker.jsx
  src/inputs/input/input.jsx
  src/inputs/phoneInput/phoneInput.jsx
  src/inputs/phoneInput/phoneInputCountryDropdown.jsx
  src/inputs/radio/radio.jsx
  src/inputs/select/select.jsx
  src/inputs/textArea/textArea.jsx
  src/inputs/timePicker/timePicker.jsx
  src/surfaces/actionBar/actionBarActionsButtonDrawerOption.jsx
  src/surfaces/actionBar/actionBarActionsButtonDrawerSubOption.jsx
  src/surfaces/modalDeprecated/__test__/modalDeprecated.test.js
Labels: enhancement, priority: medium, risk: medium

#366 [hotfix/10.3.9-hotfix] Bug AB#66203 [My Ministries > Serving Opps] - User cannot click on the checkbox to edit the venue Capacity, when creating a new SO
  src/dataDisplay/personPanel/__test__/personPanelDetails.test.js
  src/dataDisplay/personPanel/__test__/personPanelDetailsActionButton.test.js
  src/dataDisplay/personPanel/personPanelSummary.jsx
  src/global/constants.js
  src/global/keyCode.js
  src/inputs/input/input.jsx
  src/inputs/prompt/prompt.jsx
  src/inputs/radio/radio.jsx
  src/navigation/a/a.jsx
Labels: bug, priority: high, risk: medium
