Repository saddlebackdev/react-cm-ui, pull requests merged in 2022-01, with the labels that each got.

#345 [dev] PBI AB#60342: Minor Table Fixes
  docs/src/app/navigationConstants.js
  docs/src/dataDisplay/table/api/api.jsx
  docs/src/dataDisplay/table/api/index.js
  docs/src/dataDisplay/table/table.jsx
  src/dataDisplay/table/table.d.ts
  src/dataDisplay/table/table.jsx
  src/dataDisplay/table/table.scss
  src/dataDisplay/table/tableCell.scss
  src/style.scss
Labels: bug

#346 [dev] PBI AB#60342: Drawer Types and Table Type Fixes
  src/dataDisplay/chip/chip.d.ts
  src/dataDisplay/label/label.d.ts
  src/dataDisplay/table/index.d.ts
  src/dataDisplay/table/table.d.ts
  src/surfaces/drawer/drawer.d.ts
  src/surfaces/drawer/drawerActionBar.d.ts
  src/surfaces/drawer/drawerContent.d.ts
  src/surfaces/drawer/drawerDataCards.d.ts
  src/surfaces/drawer/drawerDataGrid.d.ts
  src/surfaces/drawer/drawerDataGroups.d.ts
  src/surfaces/drawer/drawerTitleBar.d.ts
  src/surfaces/drawer/index.d.ts
Labels: enhancement, priority: medium, risk: medium

#347 [dev] Related to AB#58900 DatePickerInput enhancements
  docs/src/app/navigationConstants.js
  docs/src/inputs/datePickerInput/api/api.jsx
  docs/src/inputs/datePickerInput/api/index.js
  docs/src/inputs/datePickerInput/datePickerInput.jsx
  docs/src/inputs/datePickerInput/devSandbox/devSandbox.jsx
  docs/src/inputs/datePickerInput/devSandbox/index.js
  docs/src/inputs/datePickerInput/examples/exampleDatePickerInputBasic.jsx
  docs/src/inputs/datePickerInput/examples/exampleDatePickerInputDisabled.jsx
  docs/src/inputs/datePickerInput/examples/exampleDatePickerInputEvents.jsx
  docs/src/inputs/datePickerInput/examples/exampleDatePickerInputExcludeDates.jsx
  docs/src/inputs/datePickerInput/examples/exampleDatePickerInputFilterDates.jsx
  docs/src/inputs/datePickerInput/examples/exampleDatePickerInputFluid.jsx
  docs/src/inputs/datePickerInput/examples/exampleDatePickerInputIncludeDates.jsx
  docs/src/inputs/datePickerInput/examples/exampleDatePickerInputLabel.jsx
  docs/src/inputs/datePickerInput/examples/exampleDatePickerInputMaxDate.jsx
  docs/src/inputs/datePickerInput/examples/exampleDatePickerInputMinDate.jsx
  docs/src/inputs/datePickerInput/examples/exampleDatePickerInputOnChange.jsx
  docs/src/inputs/datePickerInput/examples/exampleDatePickerInputOnMonthChange.jsx
  docs/src/inputs/datePickerInput/examples/exampleDatePickerInputRange.jsx
  docs/src/inputs/datePickerInput/examples/exampleDatePickerinputLocale.jsx
  docs/src/inputs/timePicker/devSandbox/devSandbox.jsx
  src/inputs/datePickerInput/__test__/datePickerInput.test.js
  src/inputs/datePickerInput/datePickerInput.jsx
  src/inputs/input/input.jsx
  src/versions.js
Labels: enhancement, priority: medium, docs, risk: medium

#351 [dev] PBI AB#60342: Added data-testid To Drawer Container
  src/surfaces/drawer/drawer.jsx
Labels: enhancement

#349 [dev] Related to AB#58900 Add some data-testid support for <ModalDeprecated> and add Close Button data-testid to <Modal>
  src/surfaces/modal/__test__/modal.test.js
  src/surfaces/modal/index.d.ts
  src/surfaces/modal/modal.d.ts
  src/surfaces/modal/modal.jsx
  src/surfaces/modal/modalActions.d.ts
  src/surfaces/modal/modalContent.d.ts
  src/surfaces/modal/modalHeader.jsx
  src/surfaces/modalDeprecated/__test__/modalDeprecated.test.js
  src/surfaces/modalDeprecated/modalDeprecated.jsx
  src/surfaces/modalDeprecated/modalDeprecatedHeader.jsx
Labels: enhancement, priority: medium, risk: low

#352 [dev] AB#60935 Information on the table is being overlapped
  src/surfaces/actionBar/actionBar.jsx
  src/surfaces/actionBar/actionBarSearch.jsx
Labels: enhancement, priority: medium, risk: low
