Repository saddlebackdev/react-cm-ui, pull requests merged in 2023-11, with the labels that each got.

#473 [dev] AB#93147 - Dropdown Button Options not hiding even after clicked
  docs/src/inputs/dropdownButton/examples/dropdownButtonExample.jsx
  src/dataDisplay/image/image.jsx
  src/inputs/dropdownMenu/dropdownMenuOption.jsx
  src/surfaces/actionBar/actionBarActionsButtonDrawerOption.jsx
Labels: bug, priority: high, risk: medium

#476 [hotfix/10.7.3-hotfix/1] AB#102944 -- add new icons for sections in the Journey Builder
  docs/src/dataDisplay/icon/icon.jsx
  src/dataDisplay/icon/icon.jsx
Labels: enhancement, priority: high, risk: low

#474 [dev] [No PBI] - Implementing Action Buttons (Apply Filter & Clear All) on filter rails
  docs/src/layout/page/demo/demoFiltersRail.jsx
  docs/src/surfaces/drawer/demo/demoDrawer.jsx
  src/layout/page/pageFiltersRail.jsx
  src/surfaces/drawer/drawerFiltersRail.jsx
  src/surfaces/filtersRail/__test__/filtersRail.test.js
  src/surfaces/filtersRail/filtersRail.jsx
Labels: enhancement, priority: high, risk: medium

#477 [dev] PBI AB#103112 [Data Capture - Connection Form - Entries] Ability to Read a Sensitive Connection Question Answer
  docs/src/inputs/checkbox/checkbox.jsx
  docs/src/inputs/input/devSandbox/devSandbox.jsx
  docs/src/inputs/input/examples/exampleInputIsRedacted.jsx
  docs/src/inputs/radio/radio.jsx
  docs/src/inputs/select/devSandbox/devSandbox.jsx
  docs/src/inputs/select/examples/exampleIsRedactedSelect.jsx
  docs/src/inputs/textArea/textArea.jsx
  src/inputs/checkbox/checkbox.jsx
  src/inputs/greyScreenGuard/checkboxScreenGuard.jsx
  src/inputs/greyScreenGuard/index.ts
  src/inputs/greyScreenGuard/inputScreenGuard.jsx
  src/inputs/greyScreenGuard/radioScreenGuard.jsx
  src/inputs/greyScreenGuard/selectScreenGuard.jsx
  src/inputs/input/input.jsx
  src/inputs/radio/radio.jsx
  src/inputs/select/select.jsx
  src/inputs/textArea/textArea.jsx
Labels: enhancement, priority: medium, risk: medium

#478 [dev] PBI AB#103112 [Data Capture - Connection Form - Entries] Ability to Read a Sensitive Connection Question Answer
  docs/src/inputs/datePickerInput/devSandbox/devSandbox.jsx
  docs/src/inputs/datePickerInput/examples/exampleDatePickerInputIsRedacted.jsx
  docs/src/inputs/input/examples/exampleInputIsRedacted.jsx
  src/inputs/datePickerInput/datePickerInput.jsx
  src/inputs/greyScreenGuard/checkboxScreenGuard.jsx
  src/inputs/greyScreenGuard/inputScreenGuard.jsx
  src/inputs/greyScreenGuard/radioScreenGuard.jsx
  src/inputs/input/input.jsx
Labels: enhancement, priority: medium, risk: medium

#479 [dev] Bug AB#103415: [Event Central][Paid Events 2.0] - An additional "0" (zero) will be added automatically (at the beginning of the Price of the Ticket amount), when user tries to Edit the Ticket's Regular price field
  docs/src/inputs/input/examples/exampleInputType.jsx
  src/inputs/input/input.jsx
Labels: bug, enhancement, priority: medium, risk: low

#482 [dev][No PBI] - Fixed clear all disabling issue on filter rails when applying filter buttons
  src/surfaces/filtersRail/filtersRail.jsx
Labels: bug, priority: medium, risk: low
