Repository saddlebackdev/react-cm-ui, pull requests merged in 2023-10, with the labels that each got.

#465 [dev] AB#102323 [Finance > COA > Edit Sub Account] - User can Edit the "Sub Account's" segments code numbers, in the "Edit Sub Account" drawer.
  src/inputs/selectNext/selectNext.tsx
Labels: enhancement, priority: medium, risk: low

#466 [dev] BUG AB#102385 - [Finance > Segments & Codes > Edit Code] - User should be able to nullify the "Associated HC Campus" (if they want to) of a Campus code, in the drop down menu, as it is not a required field
  src/inputs/selectNext/selectNext.tsx
Labels: enhancement

#468 [dev] [No PBI] - Fixing z-index conflict between Snackbar & Drawer Overlay
  src/feedback/snackbar/snackbar.jsx
Labels: bug, priority: medium, risk: low

#467 [dev] Bug AB#100081: [My Serving Opps][My Ministries>SO] - Previously selected menu option(s) are remining open, when user selects any other menu option
  docs/src/inputs/dropdownButton/dropdownButton.jsx
  docs/src/inputs/dropdownButton/examples/dropdownButtonExample.jsx
  docs/src/inputs/dropdownButton/examples/dropdownButtonStopPropagationExample.jsx
  src/inputs/dropdownButton/dropdownButton.jsx
  src/inputs/dropdownMenu/dropdownMenu.jsx
Labels: bug, priority: medium, risk: medium

#471 [dev] Bug AB#44007 [Automated Test][Mobile][Ministry Central] Close button div overlapping on apply filter button
  src/surfaces/drawer/drawerTitleBar.scss
Labels: bug, priority: medium, risk: medium
