Repository saddlebackdev/react-cm-ui, pull requests merged in 2023-07, with the labels that each got.

#448 [dev] [No PBI or Bug] Package upgrades in `/docs` project
  docs/package-lock.json
  docs/package.json
Labels: dependencies, priority: medium, risk: medium

#447 [dev] [No PBI or Bug] React CM UI bug fixes and enhancements
  .eslintrc
  .gitattributes
  docs/src/dataDisplay/icon/devSandbox/devSandbox.jsx
  docs/src/dataDisplay/icon/devSandbox/examples/exampleHealthyChurchFeatures.jsx
  docs/src/dataDisplay/icon/icon.jsx
  docs/src/feedback/activityIndicator/activityIndicatorStyleExample.jsx
  docs/src/global/block.scss
  docs/src/global/highlighter.scss
  docs/src/global/swatch.scss
  docs/src/global/tableProps.jsx
  docs/src/global/tableProps.scss
  docs/src/inputs/buttonGroup/buttonGroup.jsx
  docs/src/inputs/buttonGroup/devSandbox/devSandbox.jsx
  docs/src/inputs/datePickerInput/examples/exampleDatePickerInputLocale.jsx
  docs/src/inputs/durationPicker/durationPicker.jsx
  docs/src/inputs/input/examples/exampleInputType.jsx
  docs/src/surfaces/drawer/drawerDataGrid.jsx
  docs/tsconfig.json
  src/dataDisplay/icon/icon.jsx
  src/global/keyCode.js
  src/inputs/input/input.jsx
  src/layout/container/container.jsx
  src/surfaces/actionBar/actionBar.jsx
Labels: bug, enhancement, priority: medium, risk: medium

#449 [dev] AB#53618 [DevOps] Convert Build Pipelines to Yaml | Create react-cm-ui YAML pipeline
  pipelines/React-CM-UI-Build.yml
Labels: enhancement, priority: medium, risk: medium, devops

#451 [dev] AB#53618 [DevOps] Convert Build Pipelines to Yaml | Update react-cm-ui pipeline.
  pipelines/React-CM-UI-Build.yml
Labels: enhancement, priority: medium, risk: low, devops

#453 [dev] [No Bug/PBI] Fix some prop type warnings in various React CM UI components
  src/inputs/buttonGroup/buttonGroup.jsx
  src/inputs/checkbox/checkbox.jsx
  src/inputs/datePickerInput/datePickerInput.jsx
  src/inputs/input/input.jsx
  src/inputs/textArea/textArea.jsx
  src/navigation/sectionalTabs/sectionalTabs.jsx
  src/surfaces/detailsWindow/detailsWindow.jsx
Labels: bug, enhancement, priority: medium, risk: low

#452 [dev] AB#93143 - [Giving Central][Giving Activity] - Ability to search for a Gift
  docs/src/layout/page/demo/demo.jsx
  docs/src/surfaces/drawer/demo/demoDrawer.jsx
  docs/src/surfaces/drawer/drawer.jsx
  docs/src/surfaces/drawer/drawerContent.jsx
  src/global/models/index.ts
  src/global/models/selectOption.model.ts
  src/inputs/select/select.jsx
  src/surfaces/actionBar/__test__/actionBar.test.tsx
  src/surfaces/actionBar/__test__/actionBarActionsButton.test.tsx
  src/surfaces/actionBar/__test__/actionBarActionsButtonDrawerOption.test.tsx
  src/surfaces/actionBar/__test__/actionBarActionsButtonDrawerSubOption.test.tsx
  src/surfaces/actionBar/__test__/actionBarSearch.test.tsx
  src/surfaces/actionBar/__test__/actionBarSearchSelect.test.tsx
  src/surfaces/actionBar/actionBar.jsx
  src/surfaces/actionBar/actionBar.scss
  src/surfaces/actionBar/actionBarActionsButton.jsx
  src/surfaces/actionBar/actionBarSearch.jsx
  src/surfaces/actionBar/actionBarSearchSelect.tsx
Labels: enhancement, priority: medium, risk: medium

#455 [dev][hotfix/1.62.3] - Bug AB#97711 - [Connection Forms][Safari] - Public form not rendering phone number country flag icon
  src/inputs/phoneInput/phoneInput.scss
Labels: bug, priority: high, risk: low

#454 [dev] [No Bug/PBI] Add `suppressBackgroundImage` prop to `<Image>` component
  docs/src/app/navigationConstants.js
  docs/src/dataDisplay/image/api/api.jsx
  docs/src/dataDisplay/image/api/index.js
  docs/src/dataDisplay/image/devSandbox/devSandbox.jsx
  docs/src/dataDisplay/image/devSandbox/examples/exampleAvatarImages.jsx
  docs/src/dataDisplay/image/devSandbox/examples/exampleImage.jsx
  docs/src/dataDisplay/image/devSandbox/examples/exampleImageSizes.jsx
  docs/src/dataDisplay/image/devSandbox/index.js
  docs/src/dataDisplay/image/image.jsx
  src/dataDisplay/image/__test__/image.test.js
  src/dataDisplay/image/image.jsx
Labels: enhancement, priority: medium, docs, risk: low

#456 [hotfix/10.6.8-hotfix-1] Bug AB#97711 - [Connection Forms][Safari] - Public form not rendering phone number country flag icon
  src/inputs/phoneInput/phoneInput.scss
Labels: bug, priority: high, risk: medium

#457 [dev] [No Bug/PBI] Fix `colorExports` SCSS/CSS import in `<Image>` component
  src/dataDisplay/image/image.jsx
Labels: bug, priority: high, risk: low
