Repository saddlebackdev/react-cm-ui, pull requests merged in 2024-04, with the labels that each got.

#490 [dev] [No PBI] Select onInputChange Prop
  src/inputs/select/select.jsx
Labels: enhancement, priority: medium, risk: low

#491 [dev] PBI AB#107487 [Data Capture] Ability to set Settings & Preferences of Connection Forms
  src/dataDisplay/chip/chip.d.ts
Labels: bug, priority: medium, risk: low

#492 [dev] Small tweaks for `<Chip>` component
  src/dataDisplay/chip/chip.d.ts
  src/dataDisplay/chip/chip.jsx
Labels: enhancement, priority: high, risk: low

#494 [dev] [No PBI Correct `color` type for `<Chip>` TypeScript declaration
  src/dataDisplay/chip/chip.d.ts
Labels: bug, priority: medium, risk: low

#496 [dev] PBI AB#107821: [People - Milestones] Ability to Activate the Membership Milestone
  docs/src/dataDisplay/personCoreMilestones/examples/constants.js
  docs/src/dataDisplay/personCoreMilestones/examples/exampleAdultFemale.jsx
  docs/src/dataDisplay/personCoreMilestones/examples/exampleChild.jsx
  docs/src/dataDisplay/personCoreMilestones/examples/exampleDisable.jsx
  docs/src/dataDisplay/personCoreMilestones/examples/exampleInteractive.jsx
  docs/src/dataDisplay/personCoreMilestones/examples/examplePersonCoreMilestones.jsx
  docs/src/dataDisplay/personCoreMilestones/examples/exampleStudent.jsx
  docs/src/dataDisplay/personCoreMilestones/examples/exampleUndefined.jsx
  docs/src/dataDisplay/personPanel/personPanelConstants.js
  docs/src/dataDisplay/personPanel/personPanelControlledAccordionExample.jsx
  docs/src/dataDisplay/personPanel/personPanelSimpleExample.jsx
  src/dataDisplay/personCoreMilestones/__test__/personCoreMilestones.test.js
  src/dataDisplay/personCoreMilestones/constants.js
  src/dataDisplay/personCoreMilestones/gridColumnClassBaseballDiamond.jsx
  src/dataDisplay/personCoreMilestones/personCoreMilestones.jsx
  src/dataDisplay/personPanel/__test__/personPanelDetails.test.js
  src/dataDisplay/personPanel/personPanelDetails.jsx
Labels: enhancement, priority: high, risk: medium
